export const UI_DEFAULTS = {
  fontDisplay: "'Outfit', sans-serif",
  fontBody: "'Inter', sans-serif",
  team1Color: '#FF3333',
  team2Color: '#3366FF',
  team1Label: 'Player 1',
  team2Label: 'Player 2',
  team1Dark: '#CC0000',
  team2Dark: '#0033CC',
  glassOpacity: 0.6,
  glassBlur: '24px',
  fadeDuration: '0.4s',
  hpBarWidth: 30,
  hpBarHeight: 4,
  hpBarOffset: 15,
  pieceGlowBlur: 20,
  traceLineWidth: 3,
  traceColor: '#FF3333',
  ghostTraceOpacity: 0.3,
  controlPointSize: 4,
  controlPointColor: '#3366FF',
  endPointColor: '#10b981',
};
