export const UI_DEFAULTS = {
  fontDisplay: "'Outfit', sans-serif",
  fontBody: "'Inter', sans-serif",
  team1Color: '#06b6d4',
  team2Color: '#f43f5e',
  team1Label: 'Player 1',
  team2Label: 'Player 2',
  team1Dark: '#0369a1',
  team2Dark: '#9f1239',
  glassOpacity: 0.6,
  glassBlur: '24px',
  fadeDuration: '0.4s',
  hpBarWidth: 30,
  hpBarHeight: 4,
  hpBarOffset: 15,
  pieceGlowBlur: 20,
  traceLineWidth: 3,
  traceColor: '#06b6d4',
  ghostTraceOpacity: 0.3,
  controlPointSize: 4,
  controlPointColor: '#f43f5e',
  endPointColor: '#10b981',
};
