use serde::Serialize;

#[derive(Serialize)]
pub struct CodebaseJson {
    pub generated: String,
    pub generator: String,
    pub note: String,
    pub files: Vec<FileInfo>,
}

#[derive(Serialize)]
pub struct FileInfo {
    pub path: String,
    #[serde(rename = "type")]
    pub file_type: String,
    pub exports: Vec<String>,
    pub description: String,
}

impl CodebaseJson {
    pub fn new(files: Vec<FileInfo>) -> Self {
        Self {
            generated: chrono::Utc::now().to_rfc3339(),
            generator: "ast-indexer".to_string(),
            note: "Auto-generated by Rust AST Indexer via git pre-commit hook.".to_string(),
            files,
        }
    }

    pub fn to_json_pretty(&self) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(self)
    }
}

impl FileInfo {
    pub fn new(path: String, file_type: String, exports: Vec<String>) -> Self {
        Self {
            path,
            file_type,
            exports,
            description: "Auto-indexed signatures".to_string(),
        }
    }
}
